import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'he' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    accounts: 'Accounts',
    campaigns: 'Campaigns',
    inbox: 'Inbox',
    contacts: 'Contacts',
    warmup: 'Warm-up',
    settings: 'Settings',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back! Here\'s what\'s happening with your campaigns.',
    'dashboard.connectedAccounts': 'Connected Accounts',
    'dashboard.messagesSentToday': 'Messages Sent Today',
    'dashboard.activeCampaigns': 'Active Campaigns',
    'dashboard.pendingMessages': 'Pending Messages',
    'dashboard.newCampaign': 'New Campaign',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addNewAccount': 'Add New Account',
    'dashboard.createCampaign': 'Create Campaign',
    'dashboard.importContacts': 'Import Contacts',
    'dashboard.startWarmup': 'Start Warm-up',
    'dashboard.noRecentActivity': 'No recent activity',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and application preferences',
    'settings.licenseInfo': 'License Information',
    'settings.licenseDetails': 'Your Yachash license details',
    'settings.licenseKey': 'License Key',
    'settings.expiresOn': 'Expires On',
    'settings.timeRemaining': 'Time Remaining',
    'settings.daysLeft': 'days left',
    'settings.accountInfo': 'Account Information',
    'settings.accountDetails': 'Your registered account details',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.language': 'Language & Region',
    'settings.chooseLanguage': 'Choose your preferred language',
    'settings.appLanguage': 'Application Language',
    'settings.languageComingSoon': '✨ Language switching is now available! The entire app will switch to your selected language.',
    'settings.appInfo': 'Application Information',
    'settings.version': 'Version',
    'settings.environment': 'Environment',
    'settings.active': 'Active',
    'settings.expired': 'Expired',
    'settings.suspended': 'Suspended',
    'settings.gracePeriod': 'Grace Period',
    'settings.invalid': 'Invalid',
    'settings.notSet': 'Not set',
    
    // Toasts
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.warning': 'Warning',
    'toast.accountDeleted': 'Account deleted successfully',
    'toast.campaignCreated': 'Campaign created successfully',
    'toast.campaignDeleted': 'Campaign deleted',
    'toast.campaignStarted': 'Campaign started successfully',
    'toast.campaignPaused': 'Campaign paused',
    'toast.campaignStopped': 'Campaign stopped',
    'toast.contactDeleted': 'Contact deleted successfully',
    'toast.tagCreated': 'Tag created successfully',
    'toast.tagDeleted': 'Tag deleted successfully',
    'toast.messageSent': 'Message sent successfully',
    'toast.fileSent': 'File sent successfully',
    'toast.markedAsHandled': 'Marked as handled',
    
    // Common
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.of': 'of',
    'common.name': 'Name',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.create': 'Create',
    'common.edit': 'Edit',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    
    // Accounts Page
    'accounts.title': 'WhatsApp Accounts',
    'accounts.subtitle': 'Manage your connected devices and proxies',
    'accounts.addAccount': 'Add Account',
    'accounts.connected': 'Connected',
    'accounts.disconnected': 'Disconnected',
    'accounts.connecting': 'Connecting',
    'accounts.noAccounts': 'No accounts connected yet',
    'accounts.noAccountsDescription': 'Connect your WhatsApp accounts to start sending campaigns and managing messages.',
    'accounts.addFirstAccount': 'Connect Your First Account',
    'accounts.bulkUpdate': 'Bulk Update',
    'accounts.refreshPictures': 'Refresh Pictures',
    'accounts.refreshing': 'Refreshing...',
    'accounts.selectionMode': 'Selection Mode',
    'accounts.exitSelection': 'Exit Selection',
    'accounts.cancelSelection': 'Cancel Selection',
    'accounts.connectNewAccount': 'Connect New Account',
    'accounts.selectedCount': '{selected} of {total} selected',
    'accounts.updateSelected': 'Update Selected',
    'accounts.totalAccounts': 'Total Accounts',
    'accounts.activeSessions': 'Active Sessions',
    'accounts.deleteAccount': 'Delete Account?',
    'accounts.deleteConfirm': 'Are you sure you want to delete this account? This will remove all associated data.',
    'accounts.refreshConfirm': 'Refresh profile pictures for {count} connected account(s)?',
    'accounts.refreshPicturesTitle': 'Refresh Profile Pictures?',
    'accounts.disconnect': 'Disconnect',
    'accounts.viewQR': 'View QR Code',
    'accounts.failedToDelete': 'Failed to delete account',
    'accounts.accountDisconnected': 'Account disconnected',
    'accounts.failedToDisconnect': 'Failed to disconnect account',
    'accounts.selectAtLeastOne': 'Please select at least one account',
    'accounts.enterNameOrImage': 'Please enter a name or select an image to update',
    'accounts.successfullyUpdated': 'Successfully updated {count} account(s)',
    'accounts.failedToUpdate': 'Failed to update accounts',
    'accounts.noConnectedToRefresh': 'No connected accounts to refresh',
    'accounts.successfullyRefreshed': 'Successfully refreshed {count} profile picture(s)!',
    'accounts.failedToRefreshPictures': 'Failed to refresh profile pictures',
    'accounts.bulkUpdateTitle': 'Bulk Update Accounts',
    'accounts.bulkUpdateDescription': 'Update {count} selected account(s)',
    'accounts.whatsappDisplayName': 'WhatsApp Display Name',
    'accounts.enterNewDisplayName': 'Enter new display name',
    'accounts.leaveEmptyNames': 'Leave empty to keep current names',
    'accounts.profilePicture': 'Profile Picture',
    'accounts.leaveEmptyPictures': 'Leave empty to keep current pictures',
    'accounts.updateAccountsButton': 'Update {count} Account(s)',
    
    // Add Account Dialog
    'addAccount.title': 'Add WhatsApp Account',
    'addAccount.description': 'Configure your WhatsApp account connection',
    'addAccount.subtitle': 'Configure your WhatsApp account connection',
    'addAccount.connectionMethod': 'Connection Method',
    'addAccount.qrCode': 'QR Code',
    'addAccount.pairingCode': 'Pairing Code',
    'addAccount.qrCodeHelper': 'Scan QR code with WhatsApp camera',
    'addAccount.pairingCodeHelper': 'Enter code manually in WhatsApp settings',
    'addAccount.qrHint': 'Scan QR code with WhatsApp camera',
    'addAccount.pairingHint': 'Enter code manually in WhatsApp settings',
    'addAccount.phoneNumber': 'Phone Number',
    'addAccount.phoneNumberPlaceholder': '+972501234567',
    'addAccount.phoneNumberHelper': 'Include country code (e.g., +1, +972)',
    'addAccount.phoneHint': 'Include country code (e.g., +1, +972)',
    'addAccount.accountName': 'Account Name (Optional)',
    'addAccount.accountNamePlaceholder': 'My Business Account',
    'addAccount.proxySettings': 'Proxy Settings (Optional)',
    'addAccount.httpOnly': 'HTTP/HTTPS Only',
    'addAccount.proxySupported': '✅ Supported: HTTP/HTTPS proxies with username/password authentication',
    'addAccount.proxyExample': 'Example: proxy.example.com:8080 with username and password',
    'addAccount.proxyType': 'Proxy Type',
    'addAccount.proxyHost': 'Proxy Host',
    'addAccount.proxyHostPlaceholder': 'proxy.example.com',
    'addAccount.proxyPort': 'Port',
    'addAccount.proxyPortPlaceholder': '8080',
    'addAccount.proxyUsername': 'Proxy Username',
    'addAccount.proxyUsernamePlaceholder': 'proxy username',
    'addAccount.proxyPassword': 'Proxy Password',
    'addAccount.proxyPasswordPlaceholder': 'proxy password',
    'addAccount.proxyAuthHelper': 'Leave empty if no auth',
    'addAccount.proxyNote': 'Only HTTP/HTTPS proxies are supported. Authentication with username/password is fully supported.',
    'addAccount.connecting': 'Connecting...',
    'addAccount.connectButton': 'Connect Account',
    'addAccount.submit': 'Connect Account',
    'addAccount.scanQR': 'Scan QR Code',
    'addAccount.enterPairing': 'Enter this code in WhatsApp',
    'addAccount.done': 'Done',
    'addAccount.errorAdd': 'Failed to add account',
    'addAccount.connected': 'Account connected successfully!',
    'addAccount.closingAutomatically': 'Closing automatically...',
    
    // Campaigns Page
    'campaigns.title': 'Campaigns',
    'campaigns.subtitle': 'Create and manage your WhatsApp campaigns',
    'campaigns.createCampaign': 'Create Campaign',
    'campaigns.noCampaigns': 'No campaigns created yet',
    'campaigns.createFirst': 'Create Your First Campaign',
    'campaigns.start': 'Start',
    'campaigns.continue': 'Continue',
    'campaigns.pause': 'Pause',
    'campaigns.stop': 'Stop',
    'campaigns.delete': 'Delete',
    'campaigns.deleteConfirm': 'Are you sure you want to delete this campaign? This action cannot be undone.',
    'campaigns.downloadReport': 'Download Excel Report',
    'campaigns.draft': 'Draft',
    'campaigns.running': 'Running',
    'campaigns.paused': 'Paused',
    'campaigns.completed': 'Completed',
    'campaigns.stopped': 'Stopped',
    
    // Create Campaign Page
    'createCampaign.title': 'Create Campaign',
    'createCampaign.subtitle': 'Set up your WhatsApp marketing campaign',
    'createCampaign.accountsAvailable': '{count} Accounts Available',
    'createCampaign.buttons.discard': 'Discard',
    'createCampaign.buttons.launch': 'Launch Campaign',
    'createCampaign.buttons.launching': 'Launching...',
    'createCampaign.step1.title': 'What to send?',
    'createCampaign.step1.description': 'Configure your campaign identity and message content',
    'createCampaign.step1.campaignName': 'Campaign Name',
    'createCampaign.step1.campaignNamePlaceholder': 'e.g. Summer Sale - VIP Customers',
    'createCampaign.step1.messageContent': 'Message Content',
    'createCampaign.step1.messagePlaceholder': 'Hi {{name}}, I wanted to reach out regarding...',
    'createCampaign.step1.personalizeHint': 'Use {{name}} to personalize',
    'createCampaign.step1.messageVariantsTitle': 'Message Variants',
    'createCampaign.step1.addMessageVariant': '+ Add Variant',
    'createCampaign.step1.messageVariantsHint': 'One variant is picked at random for each send',
    'createCampaign.step1.messageVariantLabel': 'Variant',
    'createCampaign.formatting.bold': 'Bold',
    'createCampaign.formatting.italic': 'Italic',
    'createCampaign.formatting.strikethrough': 'Strikethrough',
    'createCampaign.formatting.monospace': 'Monospace',
    'createCampaign.step2.title': 'Who to send to?',
    'createCampaign.step2.description': 'Select sending accounts and target audience tags',
    'createCampaign.step2.sendFromAccounts': 'Send from Accounts',
    'createCampaign.step2.selectAll': 'Select All',
    'createCampaign.step2.deselectAll': 'Deselect All',
    'createCampaign.step2.unnamed': 'Unnamed',
    'createCampaign.step2.targetAudience': 'Target Audience (Tags)',
    'createCampaign.step2.noTags': 'No tags found. Go to Contacts to create tags.',
    'createCampaign.step3.title': 'When to send?',
    'createCampaign.step3.description': 'Configure delay between messages and daily limits',
    'createCampaign.step3.delayBetweenMessages': 'Delay Between Messages',
    'createCampaign.step3.minDelay': 'Min Delay',
    'createCampaign.step3.maxDelay': 'Max Delay',
    'createCampaign.step3.dailyLimit': 'Daily Limit',
    'createCampaign.step3.msgsPerAccount': 'msgs / account',
    'createCampaign.step3.workingHours': 'Working Hours',
    'createCampaign.step3.startTime': 'Start Time',
    'createCampaign.step3.endTime': 'End Time',
    'createCampaign.step3.alwaysOn': 'Always On (24/7)',
    'createCampaign.step3.set24_7': 'Set 24/7',
    'createCampaign.preview.title': 'Live Preview',
    'createCampaign.preview.whatsappWeb': 'WhatsApp Web',
    'createCampaign.summary.title': 'Campaign Summary',
    'createCampaign.summary.selectedAccounts': 'Selected Accounts',
    'createCampaign.summary.targetTags': 'Target Tags',
    'createCampaign.summary.estDailyVolume': 'Est. Daily Volume',
    'createCampaign.summary.msgsCount': '~{count} msgs',
    'createCampaign.validation.campaignNameRequired': 'Please enter a campaign name',
    'createCampaign.validation.messageRequired': 'Please enter a message',
    'createCampaign.validation.accountRequired': 'Please select at least one account',
    'createCampaign.validation.tagRequired': 'Please select at least one tag',
    'createCampaign.toast.success': 'Campaign created successfully!',
    'createCampaign.toast.error': 'Failed to create campaign',
    'createCampaign.whatsappPreview.contactName': 'John Doe',
    'createCampaign.whatsappPreview.online': 'online',
    'createCampaign.whatsappPreview.today': 'Today',
    'createCampaign.whatsappPreview.defaultMessage': 'Hey! Check out our new offers.',
    'createCampaign.whatsappPreview.inputPlaceholder': 'Message',
    'createCampaign.scheduling.enableScheduling': 'Schedule campaign for later',
    'createCampaign.scheduling.startDateTime': 'Start Date & Time',
    'createCampaign.scheduling.scheduledFor': 'Scheduled for {datetime}',
    
    // Inbox Page
    'inbox.title': 'Inbox',
    'inbox.searchChats': 'Search chats...',
    'inbox.allStatus': 'All Status',
    'inbox.unhandled': 'Unhandled',
    'inbox.handled': 'Handled',
    'inbox.allAccounts': 'All Accounts',
    'inbox.chats': 'chats',
    'inbox.selectChat': 'Select a chat to start messaging',
    'inbox.manageConversations': 'Manage all your WhatsApp conversations in one place',
    'inbox.markHandled': 'Mark Handled',
    'inbox.typeMessage': 'Type a message...',
    'inbox.sendMessage': 'Send message',
    'inbox.attachFile': 'Attach file',
    'inbox.noChats': 'No chats found',
    
    // Media types for inbox preview
    'inbox.media.image': 'Image',
    'inbox.media.video': 'Video',
    'inbox.media.audio': 'Audio',
    'inbox.media.document': 'File',
    
    // Contacts Page
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Manage your contact list and tags',
    'contacts.importContacts': 'Import Contacts',
    'contacts.exportContacts': 'Export Contacts',
    'contacts.downloadSample': 'Download Sample',
    'contacts.noContacts': 'No contacts found',
    'contacts.deleteContact': 'Delete Contact?',
    'contacts.deleteConfirm': 'Are you sure you want to delete this contact? This action cannot be undone.',
    'contacts.manageTags': 'Manage Tags',
    'contacts.phoneNumber': 'Phone Number',
    'contacts.tags': 'Tags',
    'contacts.createdAt': 'Created At',
    'contacts.importTitle': 'Import Contacts',
    'contacts.importDesc': 'Upload a CSV or XLSX file with columns: phone_number, name (optional), tags (optional - comma separated)',
    'contacts.selectFile': 'Select File',
    'contacts.selected': 'Selected',
    'contacts.importing': 'Importing...',
    'contacts.manageTagsFor': 'Manage Tags for {name}',
    'contacts.availableTags': 'Available Tags',
    'contacts.newTag': 'New Tag',
    'contacts.tagName': 'Tag name',
    'contacts.createTag': 'Create',
    'contacts.noTags': 'No tags available',
    'contacts.deleteTag': 'Delete Tag?',
    'contacts.deleteTagConfirm': 'Are you sure you want to delete this tag? This will remove it from all contacts.',
    'contacts.done': 'Done',
    'contacts.unknownContact': 'Unknown Contact',
    'contacts.added': 'Added',
    'contacts.noTagsForContact': 'No tags',
    'contacts.manageTagsTooltip': 'Manage Tags',
    'contacts.deleteContactTooltip': 'Delete Contact',
    'contacts.importSuccess': 'Successfully imported {count} contacts',
    'contacts.blacklistInfo': 'Contacts with BlackList tag will not receive campaign messages. Use this to prevent sending to specific contacts.',
    'contacts.systemTag': 'System',
    'contacts.cannotDeleteSystem': 'Cannot delete system tag',
    'contacts.addManually': 'Add Contact',
    'contacts.addContact': 'Add New Contact',
    'contacts.contactName': 'Contact Name',
    'contacts.selectTag': 'Select Tag (optional)',
    'contacts.addSuccess': 'Contact added successfully',
    'contacts.phoneRequired': 'Phone number is required',
    'contacts.phoneInvalid': 'Please enter a valid phone number',
    'contacts.pasteNumbers': 'Paste Numbers',
    'contacts.pasteNumbersTitle': 'Paste Phone Numbers',
    'contacts.pasteNumbersDesc': 'Paste a list of phone numbers (one per line or separated by commas)',
    'contacts.pasteHere': 'Paste phone numbers here...',
    'contacts.fromFile': 'From File',
    'contacts.fromPaste': 'Paste List',
    'contacts.numbersFound': '{count} numbers found',
    
    // Warm-up Page
    'warmup.title': 'Account Warm-up',
    'warmup.subtitle': 'Gradually warm up your accounts to avoid bans',
    'warmup.configure': 'Configure Warm-up Session',
    'warmup.selectAccounts': 'Select Accounts (minimum 2)',
    'warmup.selected': 'selected',
    'warmup.minDelay': 'Min Delay (seconds)',
    'warmup.maxDelay': 'Max Delay (seconds)',
    'warmup.minutes': 'minutes',
    'warmup.smartLimits': 'Smart Limits Applied:',
    'warmup.maxMessages': 'Max 40 messages per account per day',
    'warmup.activeHours': 'Active hours: 8:00 AM - 10:00 PM',
    'warmup.parallelWork': 'All accounts work in parallel',
    'warmup.autoReset': 'Auto-reset at midnight',
    'warmup.startSession': 'Start Warm-up Session',
    'warmup.stopSession': 'Stop Session',
    'warmup.sessionActive': 'Warm-up Session Active',
    'warmup.messagesSent': 'Messages Sent Today',
    'warmup.nextMessage': 'Next Message In',
    'warmup.noActiveSession': 'No active warm-up session',
    'warmup.statistics': 'Warm-up Statistics',
    'warmup.totalSent': 'Total Sent',
    'warmup.lastMessage': 'Last Message',
    'warmup.recentActivity': 'Recent Activity',
    'warmup.sentFrom': 'Sent from',
    'warmup.sentTo': 'to',
    'warmup.noActivity': 'No warm-up activity yet',
    'warmup.sessionHistory': 'Session History',
    'warmup.viewDetails': 'View Details',
    'warmup.messagesInSession': 'messages',
    'warmup.accountsParticipated': 'accounts',
    'warmup.sessionDetails': 'Session Details',
    'warmup.accountBreakdown': 'Breakdown by Account',
    
    // Message Templates
    templates: 'Message Templates',
    'templates.title': 'Message Templates',
    'templates.subtitle': 'Create and manage reusable message templates',
    'templates.createNew': 'Create Template',
    'templates.noTemplates': 'No templates yet. Create your first message template!',
    'templates.templateName': 'Template Name',
    'templates.messageContent': 'Message Content',
    'templates.editTemplate': 'Edit Template',
    'templates.deleteTemplate': 'Delete Template',
    'templates.deleteConfirm': 'Are you sure you want to delete this template?',
    'templates.useTemplate': 'Use Template',
    'templates.loadTemplate': 'Load Template',
    'templates.selectTemplate': 'Select a Template',
    
    // Automation Flows
    flows: 'Automation Flows',
    'flows.title': 'Automation Flows',
    'flows.subtitle': 'Build automated chatbots to respond to incoming messages',
    'flows.createNew': 'Create New Flow',
    'flows.editFlow': 'Edit Flow',
    'flows.flowName': 'Flow Name',
    'flows.flowDescription': 'Description',
    'flows.selectAccounts': 'Select Accounts',
    'flows.activeFlow': 'Active',
    'flows.inactiveFlow': 'Inactive',
    'flows.deleteFlow': 'Delete Flow',
    'flows.deleteConfirm': 'Are you sure you want to delete this flow?',
    'flows.noFlows': 'No flows yet. Create your first automated flow!',
    'flows.saveFlow': 'Save Flow',
    'flows.nodeTypes': 'Node Types',
    'flows.conditions': 'Conditions',
    'flows.actions': 'Actions',
    'flows.ifContains': 'If Contains',
    'flows.ifEquals': 'If Equals',
    'flows.ifLastMessageOlderThan': 'If Last Message Older Than',
    'flows.hours': 'hours',
    'flows.minutes': 'minutes',
    'flows.sendMessage': 'Send Message',
    'flows.autoReply': 'Automatic Reply',
    'flows.forwardMessage': 'Forward to Number',
    'flows.delay': 'Delay',
    'flows.randomDelay': 'Random Delay',
    'flows.typing': 'Typing',
    'flows.blacklist': 'Add to BlackList',
    'flows.blacklistDescription': 'Add this contact to the BlackList',
    'flows.enterText': 'Enter text to match',
    'flows.enterMessage': 'Enter message to send',
    'flows.destinationNumber': 'Destination Number',
    'flows.enterDestinationNumber': 'Enter phone number',
    'flows.messageVariables': 'Message Variables',
    'flows.insertIncomingMessage': 'Insert incoming message',
    'flows.insertSenderPhone': 'Insert sender phone',
    'flows.seconds': 'seconds',
    'flows.minSeconds': 'Min (seconds)',
    'flows.maxSeconds': 'Max (seconds)',
    'flows.selectMedia': 'Select Media (optional)',
    'flows.caption': 'Caption',
    'flows.dragNodes': 'Drag nodes here to build your flow',
    'flows.connectNodes': 'Connect nodes to create automation logic',
    'flows.yes': 'Yes',
    'flows.no': 'No',
    'flows.next': 'Next',
    'flows.duplicate': 'Duplicate',
    'flows.remove': 'Remove',
    'flows.selectAll': 'Select All',
    'flows.clearAll': 'Clear All',
  },
  he: {
    // Navigation
    dashboard: 'לוח בקרה',
    accounts: 'חשבונות',
    campaigns: 'קמפיינים',
    inbox: 'תיבת דואר',
    contacts: 'אנשי קשר',
    warmup: 'חימום',
    settings: 'הגדרות',
    
    // Dashboard
    'dashboard.welcome': 'ברוך שובך! הנה מה שקורה עם הקמפיינים שלך.',
    'dashboard.connectedAccounts': 'חשבונות מחוברים',
    'dashboard.messagesSentToday': 'הודעות שנשלחו היום',
    'dashboard.activeCampaigns': 'קמפיינים פעילים',
    'dashboard.pendingMessages': 'הודעות ממתינות',
    'dashboard.newCampaign': 'קמפיין חדש',
    'dashboard.recentActivity': 'פעילות אחרונה',
    'dashboard.quickActions': 'פעולות מהירות',
    'dashboard.addNewAccount': 'הוסף חשבון חדש',
    'dashboard.createCampaign': 'צור קמפיין',
    'dashboard.importContacts': 'ייבא אנשי קשר',
    'dashboard.startWarmup': 'התחל חימום',
    'dashboard.noRecentActivity': 'אין פעילות אחרונה',
    
    // Settings
    'settings.title': 'הגדרות',
    'settings.subtitle': 'נהל את החשבון וההעדפות שלך',
    'settings.licenseInfo': 'מידע רישיון',
    'settings.licenseDetails': 'פרטי הרישיון שלך ב-Yachash',
    'settings.licenseKey': 'מפתח רישיון',
    'settings.expiresOn': 'פג תוקף ב',
    'settings.timeRemaining': 'זמן נותר',
    'settings.daysLeft': 'ימים נותרו',
    'settings.accountInfo': 'מידע חשבון',
    'settings.accountDetails': 'פרטי החשבון הרשום שלך',
    'settings.name': 'שם',
    'settings.email': 'אימייל',
    'settings.language': 'שפה ואזור',
    'settings.chooseLanguage': 'בחר את השפה המועדפת עליך',
    'settings.appLanguage': 'שפת האפליקציה',
    'settings.languageComingSoon': '✨ החלפת שפה זמינה! כל האפליקציה תעבור לשפה שבחרת.',
    'settings.appInfo': 'מידע אפליקציה',
    'settings.version': 'גרסה',
    'settings.environment': 'סביבה',
    'settings.active': 'פעיל',
    'settings.expired': 'פג תוקף',
    'settings.suspended': 'מושעה',
    'settings.gracePeriod': 'תקופת חסד',
    'settings.invalid': 'לא תקף',
    'settings.notSet': 'לא הוגדר',
    
    // Toasts
    'toast.success': 'הצלחה',
    'toast.error': 'שגיאה',
    'toast.warning': 'אזהרה',
    'toast.accountDeleted': 'החשבון נמחק בהצלחה',
    'toast.campaignCreated': 'הקמפיין נוצר בהצלחה',
    'toast.campaignDeleted': 'הקמפיין נמחק',
    'toast.campaignStarted': 'הקמפיין התחיל בהצלחה',
    'toast.campaignPaused': 'הקמפיין הושהה',
    'toast.campaignStopped': 'הקמפיין נעצר',
    'toast.contactDeleted': 'איש הקשר נמחק בהצלחה',
    'toast.tagCreated': 'התג נוצר בהצלחה',
    'toast.tagDeleted': 'התג נמחק בהצלחה',
    'toast.messageSent': 'ההודעה נשלחה בהצלחה',
    'toast.fileSent': 'הקובץ נשלח בהצלחה',
    'toast.markedAsHandled': 'סומן כטופל',
    
    // Common
    'common.cancel': 'ביטול',
    'common.delete': 'מחק',
    'common.save': 'שמור',
    'common.add': 'הוסף',
    'common.close': 'סגור',
    'common.loading': 'טוען...',
    'common.search': 'חיפוש',
    'common.selectAll': 'בחר הכל',
    'common.deselectAll': 'בטל בחירת הכל',
    'common.of': 'מתוך',
    'common.name': 'שם',
    'common.status': 'סטטוס',
    'common.actions': 'פעולות',
    'common.create': 'צור',
    'common.edit': 'ערוך',
    'common.refresh': 'רענן',
    'common.export': 'ייצא',
    'common.import': 'ייבא',
    
    // Accounts Page
    'accounts.title': 'חשבונות ווטסאפ',
    'accounts.subtitle': 'נהל את המכשירים והפרוקסים המחוברים שלך',
    'accounts.addAccount': 'הוסף חשבון',
    'accounts.connected': 'מחובר',
    'accounts.disconnected': 'מנותק',
    'accounts.connecting': 'מתחבר',
    'accounts.noAccounts': 'אין חשבונות מחוברים עדיין',
    'accounts.noAccountsDescription': 'חבר את חשבונות הווטסאפ שלך כדי להתחיל לשלוח קמפיינים ולנהל הודעות.',
    'accounts.addFirstAccount': 'חבר את החשבון הראשון שלך',
    'accounts.bulkUpdate': 'עדכון מרובה',
    'accounts.refreshPictures': 'רענן תמונות',
    'accounts.refreshing': 'מרענן...',
    'accounts.selectionMode': 'מצב בחירה',
    'accounts.exitSelection': 'צא ממצב בחירה',
    'accounts.cancelSelection': 'ביטול בחירה',
    'accounts.connectNewAccount': 'חבר חשבון חדש',
    'accounts.selectedCount': '{selected} מתוך {total} נבחרו',
    'accounts.updateSelected': 'עדכן נבחרים',
    'accounts.totalAccounts': 'סך החשבונות',
    'accounts.activeSessions': 'סשנים פעילים',
    'accounts.deleteAccount': 'למחוק חשבון?',
    'accounts.deleteConfirm': 'האם אתה בטוח שברצונך למחוק חשבון זה? פעולה זו תסיר את כל הנתונים המשויכים.',
    'accounts.refreshConfirm': 'לרענן תמונות פרופיל עבור {count} חשבונות מחוברים?',
    'accounts.refreshPicturesTitle': 'לרענן תמונות פרופיל?',
    'accounts.disconnect': 'נתק',
    'accounts.viewQR': 'הצג קוד QR',
    'accounts.failedToDelete': 'נכשל במחיקת החשבון',
    'accounts.accountDisconnected': 'החשבון נותק',
    'accounts.failedToDisconnect': 'נכשל בניתוק החשבון',
    'accounts.selectAtLeastOne': 'אנא בחר לפחות חשבון אחד',
    'accounts.enterNameOrImage': 'אנא הזן שם או בחר תמונה לעדכון',
    'accounts.successfullyUpdated': 'עודכנו בהצלחה {count} חשבונות',
    'accounts.failedToUpdate': 'נכשל בעדכון החשבונות',
    'accounts.noConnectedToRefresh': 'אין חשבונות מחוברים לרענון',
    'accounts.successfullyRefreshed': 'רוענן בהצלחה {count} תמונות פרופיל!',
    'accounts.failedToRefreshPictures': 'נכשל ברענון תמונות הפרופיל',
    'accounts.bulkUpdateTitle': 'עדכון מרובה של חשבונות',
    'accounts.bulkUpdateDescription': 'עדכן {count} חשבונות נבחרים',
    'accounts.whatsappDisplayName': 'שם תצוגה בווטסאפ',
    'accounts.enterNewDisplayName': 'הזן שם תצוגה חדש',
    'accounts.leaveEmptyNames': 'השאר ריק לשמירת השמות הנוכחיים',
    'accounts.profilePicture': 'תמונת פרופיל',
    'accounts.leaveEmptyPictures': 'השאר ריק לשמירת התמונות הנוכחיות',
    'accounts.updateAccountsButton': 'עדכן {count} חשבונות',
    
    // Add Account Dialog
    'addAccount.title': 'הוסף חשבון ווטסאפ',
    'addAccount.description': 'הגדר את חיבור חשבון הווטסאפ שלך',
    'addAccount.subtitle': 'הגדר את חיבור חשבון הווטסאפ שלך',
    'addAccount.connectionMethod': 'שיטת חיבור',
    'addAccount.qrCode': 'קוד QR',
    'addAccount.pairingCode': 'קוד זיווג',
    'addAccount.qrCodeHelper': 'סרוק קוד QR עם מצלמת הווטסאפ',
    'addAccount.pairingCodeHelper': 'הזן קוד באופן ידני בהגדרות ווטסאפ',
    'addAccount.qrHint': 'סרוק קוד QR עם מצלמת הווטסאפ',
    'addAccount.pairingHint': 'הזן קוד באופן ידני בהגדרות ווטסאפ',
    'addAccount.phoneNumber': 'מספר טלפון',
    'addAccount.phoneNumberPlaceholder': '+972501234567',
    'addAccount.phoneNumberHelper': 'כלול קידומת מדינה (למשל, +1, +972)',
    'addAccount.phoneHint': 'כלול קידומת מדינה (למשל, +1, +972)',
    'addAccount.accountName': 'שם חשבון (אופציונלי)',
    'addAccount.accountNamePlaceholder': 'חשבון העסק שלי',
    'addAccount.proxySettings': 'הגדרות פרוקסי (אופציונלי)',
    'addAccount.httpOnly': 'HTTP/HTTPS בלבד',
    'addAccount.proxySupported': '✅ נתמך: פרוקסי HTTP/HTTPS עם אימות שם משתמש וסיסמה',
    'addAccount.proxyExample': 'דוגמה: proxy.example.com:8080 עם שם משתמש וסיסמה',
    'addAccount.proxyType': 'סוג פרוקסי',
    'addAccount.proxyHost': 'כתובת פרוקסי',
    'addAccount.proxyHostPlaceholder': 'proxy.example.com',
    'addAccount.proxyPort': 'פורט',
    'addAccount.proxyPortPlaceholder': '8080',
    'addAccount.proxyUsername': 'שם משתמש פרוקסי',
    'addAccount.proxyUsernamePlaceholder': 'שם משתמש לפרוקסי',
    'addAccount.proxyPassword': 'סיסמת פרוקסי',
    'addAccount.proxyPasswordPlaceholder': 'סיסמת פרוקסי',
    'addAccount.proxyAuthHelper': 'השאר ריק אם אין אימות',
    'addAccount.proxyNote': 'נתמכים רק פרוקסי HTTP/HTTPS. אימות עם שם משתמש וסיסמה נתמך במלואו.',
    'addAccount.connecting': 'מתחבר...',
    'addAccount.connectButton': 'חבר חשבון',
    'addAccount.submit': 'חבר חשבון',
    'addAccount.scanQR': 'סרוק קוד QR',
    'addAccount.enterPairing': 'הזן קוד זה בווטסאפ',
    'addAccount.done': 'סיום',
    'addAccount.errorAdd': 'נכשל בהוספת החשבון',
    'addAccount.connected': 'החשבון התחבר בהצלחה!',
    'addAccount.closingAutomatically': 'נסגר אוטומטית...',
    
    // Campaigns Page
    'campaigns.title': 'קמפיינים',
    'campaigns.subtitle': 'צור ונהל את קמפיינים הווטסאפ שלך',
    'campaigns.createCampaign': 'צור קמפיין',
    'campaigns.noCampaigns': 'לא נוצרו קמפיינים עדיין',
    'campaigns.createFirst': 'צור את הקמפיין הראשון שלך',
    'campaigns.start': 'התחל',
    'campaigns.continue': 'המשך',
    'campaigns.pause': 'השהה',
    'campaigns.stop': 'עצור',
    'campaigns.delete': 'מחק',
    'campaigns.deleteConfirm': 'האם אתה בטוח שברצונך למחוק קמפיין זה? פעולה זו לא ניתנת לביטול.',
    'campaigns.downloadReport': 'הורד דוח Excel',
    'campaigns.draft': 'טיוטה',
    'campaigns.running': 'רץ',
    'campaigns.paused': 'מושהה',
    'campaigns.completed': 'הושלם',
    'campaigns.stopped': 'נעצר',
    
    // Create Campaign Page
    'createCampaign.title': 'צור קמפיין',
    'createCampaign.subtitle': 'הגדר את קמפיין השיווק שלך בווטסאפ',
    'createCampaign.accountsAvailable': '{count} חשבונות זמינים',
    'createCampaign.buttons.discard': 'בטל',
    'createCampaign.buttons.launch': 'הפעל קמפיין',
    'createCampaign.buttons.launching': 'מפעיל...',
    'createCampaign.step1.title': 'מה לשלוח?',
    'createCampaign.step1.description': 'הגדר את זהות הקמפיין ותוכן ההודעה',
    'createCampaign.step1.campaignName': 'שם קמפיין',
    'createCampaign.step1.campaignNamePlaceholder': 'למשל מבצע קיץ - לקוחות VIP',
    'createCampaign.step1.messageContent': 'תוכן הודעה',
    'createCampaign.step1.messagePlaceholder': 'שלום {{name}}, רציתי ליצור קשר בנוגע ל...',
    'createCampaign.step1.personalizeHint': 'השתמש ב-{{name}} להתאמה אישית',
    'createCampaign.step1.messageVariantsTitle': 'גרסאות הודעה',
    'createCampaign.step1.addMessageVariant': '+ הוסף גרסה',
    'createCampaign.step1.messageVariantsHint': 'בכל שליחה תיבחר גרסה אחת אקראית',
    'createCampaign.step1.messageVariantLabel': 'גרסה',
    'createCampaign.formatting.bold': 'מודגש',
    'createCampaign.formatting.italic': 'נטוי',
    'createCampaign.formatting.strikethrough': 'קו חוצה',
    'createCampaign.formatting.monospace': 'מונוספייס',
    'createCampaign.step2.title': 'למי לשלוח?',
    'createCampaign.step2.description': 'בחר חשבונות שליחה ותגי קהל יעד',
    'createCampaign.step2.sendFromAccounts': 'שלח מחשבונות',
    'createCampaign.step2.selectAll': 'בחר הכל',
    'createCampaign.step2.deselectAll': 'בטל בחירת הכל',
    'createCampaign.step2.unnamed': 'ללא שם',
    'createCampaign.step2.targetAudience': 'קהל יעד (תגים)',
    'createCampaign.step2.noTags': 'לא נמצאו תגים. עבור לאנשי קשר כדי ליצור תגים.',
    'createCampaign.step3.title': 'מתי לשלוח?',
    'createCampaign.step3.description': 'הגדר עיכוב בין הודעות ומגבלות יומיות',
    'createCampaign.step3.delayBetweenMessages': 'עיכוב בין הודעות',
    'createCampaign.step3.minDelay': 'עיכוב מינימלי',
    'createCampaign.step3.maxDelay': 'עיכוב מקסימלי',
    'createCampaign.step3.dailyLimit': 'מגבלה יומית',
    'createCampaign.step3.msgsPerAccount': 'הודעות / חשבון',
    'createCampaign.step3.workingHours': 'שעות עבודה',
    'createCampaign.step3.startTime': 'שעת התחלה',
    'createCampaign.step3.endTime': 'שעת סיום',
    'createCampaign.step3.alwaysOn': 'פעיל תמיד (24/7)',
    'createCampaign.step3.set24_7': 'הגדר 24/7',
    'createCampaign.preview.title': 'תצוגה מקדימה',
    'createCampaign.preview.whatsappWeb': 'WhatsApp Web',
    'createCampaign.summary.title': 'סיכום קמפיין',
    'createCampaign.summary.selectedAccounts': 'חשבונות נבחרים',
    'createCampaign.summary.targetTags': 'תגי יעד',
    'createCampaign.summary.estDailyVolume': 'נפח יומי משוער',
    'createCampaign.summary.msgsCount': '~{count} הודעות',
    'createCampaign.validation.campaignNameRequired': 'אנא הזן שם קמפיין',
    'createCampaign.validation.messageRequired': 'אנא הזן הודעה',
    'createCampaign.validation.accountRequired': 'אנא בחר לפחות חשבון אחד',
    'createCampaign.validation.tagRequired': 'אנא בחר לפחות תג אחד',
    'createCampaign.toast.success': 'הקמפיין נוצר בהצלחה!',
    'createCampaign.toast.error': 'נכשל ביצירת הקמפיין',
    'createCampaign.whatsappPreview.contactName': 'ישראל ישראלי',
    'createCampaign.whatsappPreview.online': 'מקוון',
    'createCampaign.whatsappPreview.today': 'היום',
    'createCampaign.whatsappPreview.defaultMessage': 'היי! בדוק את ההצעות החדשות שלנו.',
    'createCampaign.whatsappPreview.inputPlaceholder': 'הודעה',
    'createCampaign.scheduling.enableScheduling': 'תזמן קמפיין למועד מאוחר יותר',
    'createCampaign.scheduling.startDateTime': 'תאריך ושעת התחלה',
    'createCampaign.scheduling.scheduledFor': 'מתוזמן ל-{datetime}',
    
    // Inbox Page
    'inbox.title': 'תיבת דואר',
    'inbox.searchChats': 'חפש שיחות...',
    'inbox.allStatus': 'כל הסטטוסים',
    'inbox.unhandled': 'לא טופל',
    'inbox.handled': 'טופל',
    'inbox.allAccounts': 'כל החשבונות',
    'inbox.chats': 'שיחות',
    'inbox.selectChat': 'בחר שיחה כדי להתחיל לשלוח הודעות',
    'inbox.manageConversations': 'נהל את כל שיחות הווטסאפ שלך במקום אחד',
    'inbox.markHandled': 'סמן כטופל',
    'inbox.typeMessage': 'הקלד הודעה...',
    'inbox.sendMessage': 'שלח הודעה',
    'inbox.attachFile': 'צרף קובץ',
    'inbox.noChats': 'לא נמצאו שיחות',
    
    // Media types for inbox preview
    'inbox.media.image': 'תמונה',
    'inbox.media.video': 'סרטון',
    'inbox.media.audio': 'הקלטה',
    'inbox.media.document': 'קובץ',
    
    // Contacts Page
    'contacts.title': 'אנשי קשר',
    'contacts.subtitle': 'נהל את רשימת אנשי הקשר והתגים שלך',
    'contacts.importContacts': 'ייבא אנשי קשר',
    'contacts.exportContacts': 'ייצא אנשי קשר',
    'contacts.downloadSample': 'הורד דוגמה',
    'contacts.noContacts': 'לא נמצאו אנשי קשר',
    'contacts.deleteContact': 'למחוק איש קשר?',
    'contacts.deleteConfirm': 'האם אתה בטוח שברצונך למחוק איש קשר זה? פעולה זו לא ניתנת לביטול.',
    'contacts.manageTags': 'נהל תגים',
    'contacts.phoneNumber': 'מספר טלפון',
    'contacts.tags': 'תגים',
    'contacts.createdAt': 'נוצר ב',
    'contacts.importTitle': 'ייבא אנשי קשר',
    'contacts.importDesc': 'העלה קובץ CSV או XLSX עם עמודות: phone_number, name (אופציונלי), tags (אופציונלי - מופרד בפסיקים)',
    'contacts.selectFile': 'בחר קובץ',
    'contacts.selected': 'נבחרו',
    'contacts.importing': 'מייבא...',
    'contacts.manageTagsFor': 'נהל תגים עבור {name}',
    'contacts.availableTags': 'תגים זמינים',
    'contacts.newTag': 'תג חדש',
    'contacts.tagName': 'שם תג',
    'contacts.createTag': 'צור',
    'contacts.noTags': 'אין תגים זמינים',
    'contacts.deleteTag': 'למחוק תג?',
    'contacts.deleteTagConfirm': 'האם אתה בטוח שברצונך למחוק תג זה? פעולה זו תסיר אותו מכל אנשי הקשר.',
    'contacts.done': 'סיום',
    'contacts.unknownContact': 'איש קשר לא ידוע',
    'contacts.added': 'נוסף ב',
    'contacts.noTagsForContact': 'אין תגים',
    'contacts.manageTagsTooltip': 'נהל תגים',
    'contacts.deleteContactTooltip': 'מחק איש קשר',
    'contacts.importSuccess': 'יובאו בהצלחה {count} אנשי קשר',
    'contacts.blacklistInfo': 'אנשי קשר עם תג BlackList לא יקבלו הודעות מקמפיינים. השתמש בזה כדי למנוע שליחה לאנשי קשר מסוימים.',
    'contacts.systemTag': 'מערכת',
    'contacts.cannotDeleteSystem': 'לא ניתן למחוק תג מערכת',
    'contacts.addManually': 'הוסף איש קשר',
    'contacts.addContact': 'הוסף איש קשר חדש',
    'contacts.contactName': 'שם איש הקשר',
    'contacts.selectTag': 'בחר תג (אופציונלי)',
    'contacts.addSuccess': 'איש הקשר נוסף בהצלחה',
    'contacts.phoneRequired': 'יש להזין מספר טלפון',
    'contacts.phoneInvalid': 'נא להזין מספר טלפון תקין',
    'contacts.pasteNumbers': 'הדבק מספרים',
    'contacts.pasteNumbersTitle': 'הדבק מספרי טלפון',
    'contacts.pasteNumbersDesc': 'הדבק רשימה של מספרי טלפון (אחד בכל שורה או מופרדים בפסיקים)',
    'contacts.pasteHere': 'הדבק מספרי טלפון כאן...',
    'contacts.fromFile': 'מקובץ',
    'contacts.fromPaste': 'הדבק רשימה',
    'contacts.numbersFound': 'נמצאו {count} מספרים',
    
    // Warm-up Page
    'warmup.title': 'חימום חשבונות',
    'warmup.subtitle': 'חמם את החשבונות שלך בהדרגה כדי למנוע חסימות',
    'warmup.configure': 'הגדר סשן חימום',
    'warmup.selectAccounts': 'בחר חשבונות (מינימום 2)',
    'warmup.selected': 'נבחרו',
    'warmup.minDelay': 'עיכוב מינימלי (שניות)',
    'warmup.maxDelay': 'עיכוב מקסימלי (שניות)',
    'warmup.minutes': 'דקות',
    'warmup.smartLimits': 'מגבלות חכמות מופעלות:',
    'warmup.maxMessages': 'מקסימום 40 הודעות לחשבון ליום',
    'warmup.activeHours': 'שעות פעילות: 8:00 בבוקר - 10:00 בערב',
    'warmup.parallelWork': 'כל החשבונות עובדים במקביל',
    'warmup.autoReset': 'איפוס אוטומטי בחצות',
    'warmup.startSession': 'התחל סשן חימום',
    'warmup.stopSession': 'עצור סשן',
    'warmup.sessionActive': 'סשן חימום פעיל',
    'warmup.messagesSent': 'הודעות שנשלחו היום',
    'warmup.nextMessage': 'הודעה הבאה בעוד',
    'warmup.noActiveSession': 'אין סשן חימום פעיל',
    'warmup.statistics': 'סטטיסטיקות חימום',
    'warmup.totalSent': 'נשלחו סה"כ',
    'warmup.lastMessage': 'הודעה אחרונה',
    'warmup.recentActivity': 'פעילות אחרונה',
    'warmup.sentFrom': 'נשלח מ',
    'warmup.sentTo': 'אל',
    'warmup.noActivity': 'אין פעילות חימום עדיין',
    'warmup.sessionHistory': 'היסטוריית סשנים',
    'warmup.viewDetails': 'הצג פרטים',
    'warmup.messagesInSession': 'הודעות',
    'warmup.accountsParticipated': 'חשבונות',
    'warmup.sessionDetails': 'פרטי סשן',
    'warmup.accountBreakdown': 'פירוט לפי חשבון',
    
    // Message Templates
    templates: 'תבניות הודעות',
    'templates.title': 'תבניות הודעות',
    'templates.subtitle': 'צור ונהל תבניות הודעות לשימוש חוזר',
    'templates.createNew': 'צור תבנית',
    'templates.noTemplates': 'אין תבניות עדיין. צור את תבנית ההודעה הראשונה שלך!',
    'templates.templateName': 'שם התבנית',
    'templates.messageContent': 'תוכן ההודעה',
    'templates.editTemplate': 'ערוך תבנית',
    'templates.deleteTemplate': 'מחק תבנית',
    'templates.deleteConfirm': 'האם אתה בטוח שברצונך למחוק תבנית זו?',
    'templates.useTemplate': 'השתמש בתבנית',
    'templates.loadTemplate': 'טען תבנית',
    'templates.selectTemplate': 'בחר תבנית',
    
    // Automation Flows
    flows: 'זרימות אוטומציה',
    'flows.title': 'זרימות אוטומציה',
    'flows.subtitle': 'בנה בוטים אוטומטיים שמגיבים להודעות נכנסות',
    'flows.createNew': 'צור זרימה חדשה',
    'flows.editFlow': 'ערוך זרימה',
    'flows.flowName': 'שם הזרימה',
    'flows.flowDescription': 'תיאור',
    'flows.selectAccounts': 'בחר חשבונות',
    'flows.activeFlow': 'פעיל',
    'flows.inactiveFlow': 'לא פעיל',
    'flows.deleteFlow': 'מחק זרימה',
    'flows.deleteConfirm': 'האם אתה בטוח שברצונך למחוק זרימה זו?',
    'flows.noFlows': 'אין זרימות עדיין. צור את הזרימה האוטומטית הראשונה שלך!',
    'flows.saveFlow': 'שמור זרימה',
    'flows.nodeTypes': 'סוגי צמתים',
    'flows.conditions': 'תנאים',
    'flows.actions': 'פעולות',
    'flows.ifContains': 'אם מכיל',
    'flows.ifEquals': 'אם שווה',
    'flows.ifLastMessageOlderThan': 'אם ההודעה האחרונה ישנה מ-',
    'flows.hours': 'שעות',
    'flows.minutes': 'דקות',
    'flows.sendMessage': 'שלח הודעה',
    'flows.autoReply': 'הודעה אוטומטית',
    'flows.forwardMessage': 'שלח למספר אחר',
    'flows.delay': 'המתנה',
    'flows.randomDelay': 'המתנה אקראית',
    'flows.typing': 'הקלדה',
    'flows.blacklist': 'הוסף לרשימה שחורה',
    'flows.blacklistDescription': 'הוסף איש קשר זה לרשימה השחורה',
    'flows.enterText': 'הזן טקסט להתאמה',
    'flows.enterMessage': 'הזן הודעה לשליחה',
    'flows.destinationNumber': 'מספר יעד',
    'flows.enterDestinationNumber': 'הזן מספר טלפון',
    'flows.messageVariables': 'משתנים להודעה',
    'flows.insertIncomingMessage': 'הוסף הודעה שהתקבלה',
    'flows.insertSenderPhone': 'הוסף מספר שולח',
    'flows.seconds': 'שניות',
    'flows.minSeconds': 'מינימום (שניות)',
    'flows.maxSeconds': 'מקסימום (שניות)',
    'flows.selectMedia': 'בחר מדיה (אופציונלי)',
    'flows.caption': 'כיתוב',
    'flows.dragNodes': 'גרור צמתים לכאן כדי לבנות את הזרימה',
    'flows.connectNodes': 'חבר צמתים ליצירת לוגיקת אוטומציה',
    'flows.yes': 'כן',
    'flows.no': 'לא',
    'flows.next': 'הבא',
    'flows.duplicate': 'שכפל',
    'flows.remove': 'הסר',
    'flows.selectAll': 'בחר הכל',
    'flows.clearAll': 'נקה הכל',
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    accounts: 'الحسابات',
    campaigns: 'الحملات',
    inbox: 'صندوق الوارد',
    contacts: 'جهات الاتصال',
    warmup: 'الإحماء',
    settings: 'الإعدادات',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بعودتك! إليك ما يحدث مع حملاتك.',
    'dashboard.connectedAccounts': 'الحسابات المتصلة',
    'dashboard.messagesSentToday': 'الرسائل المرسلة اليوم',
    'dashboard.activeCampaigns': 'الحملات النشطة',
    'dashboard.pendingMessages': 'الرسائل المعلقة',
    'dashboard.newCampaign': 'حملة جديدة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.addNewAccount': 'إضافة حساب جديد',
    'dashboard.createCampaign': 'إنشاء حملة',
    'dashboard.importContacts': 'استيراد جهات الاتصال',
    'dashboard.startWarmup': 'بدء الإحماء',
    'dashboard.noRecentActivity': 'لا يوجد نشاط حديث',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'إدارة حسابك وتفضيلات التطبيق',
    'settings.licenseInfo': 'معلومات الترخيص',
    'settings.licenseDetails': 'تفاصيل ترخيص Yachash الخاص بك',
    'settings.licenseKey': 'مفتاح الترخيص',
    'settings.expiresOn': 'ينتهي في',
    'settings.timeRemaining': 'الوقت المتبقي',
    'settings.daysLeft': 'أيام متبقية',
    'settings.accountInfo': 'معلومات الحساب',
    'settings.accountDetails': 'تفاصيل حسابك المسجل',
    'settings.name': 'الاسم',
    'settings.email': 'البريد الإلكتروني',
    'settings.language': 'اللغة والمنطقة',
    'settings.chooseLanguage': 'اختر لغتك المفضلة',
    'settings.appLanguage': 'لغة التطبيق',
    'settings.languageComingSoon': '✨ تبديل اللغة متاح! سيتحول التطبيق بالكامل إلى اللغة المحددة.',
    'settings.appInfo': 'معلومات التطبيق',
    'settings.version': 'الإصدار',
    'settings.environment': 'البيئة',
    'settings.active': 'نشط',
    'settings.expired': 'منتهي',
    'settings.suspended': 'معلق',
    'settings.gracePeriod': 'فترة السماح',
    'settings.invalid': 'غير صالح',
    'settings.notSet': 'غير محدد',
    
    // Toasts
    'toast.success': 'نجاح',
    'toast.error': 'خطأ',
    'toast.warning': 'تحذير',
    'toast.accountDeleted': 'تم حذف الحساب بنجاح',
    'toast.campaignCreated': 'تم إنشاء الحملة بنجاح',
    'toast.campaignDeleted': 'تم حذف الحملة',
    'toast.campaignStarted': 'بدأت الحملة بنجاح',
    'toast.campaignPaused': 'تم إيقاف الحملة مؤقتاً',
    'toast.campaignStopped': 'تم إيقاف الحملة',
    'toast.contactDeleted': 'تم حذف جهة الاتصال بنجاح',
    'toast.tagCreated': 'تم إنشاء العلامة بنجاح',
    'toast.tagDeleted': 'تم حذف العلامة بنجاح',
    'toast.messageSent': 'تم إرسال الرسالة بنجاح',
    'toast.fileSent': 'تم إرسال الملف بنجاح',
    'toast.markedAsHandled': 'تم وضع علامة كمعالج',
    
    // Common
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.add': 'إضافة',
    'common.close': 'إغلاق',
    'common.loading': 'جارٍ التحميل...',
    'common.search': 'بحث',
    'common.selectAll': 'تحديد الكل',
    'common.deselectAll': 'إلغاء تحديد الكل',
    'common.of': 'من',
    'common.name': 'الاسم',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    'common.create': 'إنشاء',
    'common.edit': 'تعديل',
    'common.refresh': 'تحديث',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    
    // Accounts Page
    'accounts.title': 'حسابات واتساب',
    'accounts.subtitle': 'إدارة حسابات الأعمال الخاصة بك على واتساب',
    'accounts.addAccount': 'إضافة حساب',
    'accounts.connected': 'متصل',
    'accounts.disconnected': 'غير متصل',
    'accounts.connecting': 'جارٍ الاتصال',
    'accounts.noAccounts': 'لا توجد حسابات حتى الآن',
    'accounts.addFirstAccount': 'أضف حسابك الأول',
    'accounts.bulkUpdate': 'تحديث جماعي',
    'accounts.refreshPictures': 'تحديث الصور',
    'accounts.selectionMode': 'وضع التحديد',
    'accounts.exitSelection': 'الخروج من التحديد',
    'accounts.deleteAccount': 'حذف الحساب؟',
    'accounts.deleteConfirm': 'هل أنت متأكد من حذف هذا الحساب؟ سيؤدي هذا إلى إزالة جميع البيانات المرتبطة.',
    'accounts.refreshConfirm': 'تحديث صور الملف الشخصي لـ {count} حساب متصل؟',
    'accounts.disconnect': 'قطع الاتصال',
    'accounts.viewQR': 'عرض رمز QR',
    'accounts.refreshing': 'جارٍ التحديث...',
    'accounts.totalAccounts': 'إجمالي الحسابات',
    'accounts.activeSessions': 'الجلسات النشطة',
    'accounts.noAccountsDescription': 'ابدأ بإضافة حساب واتساب الأول',
    'accounts.cancelSelection': 'إلغاء التحديد',
    'accounts.connectNewAccount': 'ربط حساب جديد',
    'accounts.selectedCount': '{selected} من {total} محدد',
    'accounts.updateSelected': 'تحديث المحدد',
    'accounts.accountDeleted': 'تم حذف الحساب',
    'accounts.failedToDelete': 'فشل حذف الحساب',
    'accounts.accountDisconnected': 'تم قطع اتصال الحساب',
    'accounts.failedToDisconnect': 'فشل قطع اتصال الحساب',
    'accounts.selectAtLeastOne': 'يرجى تحديد حساب واحد على الأقل',
    'accounts.enterNameOrImage': 'يرجى إدخال اسم أو تحديد صورة للتحديث',
    'accounts.successfullyUpdated': 'تم تحديث {count} حساب بنجاح',
    'accounts.failedToUpdate': 'فشل تحديث الحسابات',
    'accounts.noConnectedToRefresh': 'لا توجد حسابات متصلة للتحديث',
    'accounts.successfullyRefreshed': 'تم تحديث {count} صورة ملف شخصي بنجاح!',
    'accounts.failedToRefreshPictures': 'فشل تحديث صور الملف الشخصي',
    'accounts.bulkUpdateTitle': 'تحديث جماعي للحسابات',
    'accounts.bulkUpdateDescription': 'تحديث {count} حساب محدد',
    'accounts.whatsappDisplayName': 'اسم العرض في واتساب',
    'accounts.enterNewDisplayName': 'أدخل اسم عرض جديد',
    'accounts.leaveEmptyNames': 'اترك فارغاً للاحتفاظ بالأسماء الحالية',
    'accounts.profilePicture': 'صورة الملف الشخصي',
    'accounts.leaveEmptyPictures': 'اترك فارغاً للاحتفاظ بالصور الحالية',
    'accounts.updateAccountsButton': 'تحديث {count} حساب',
    
    // Add Account Dialog
    'addAccount.title': 'إضافة حساب واتساب',
    'addAccount.description': 'تكوين اتصال حساب واتساب الخاص بك',
    'addAccount.subtitle': 'تكوين اتصال حساب واتساب الخاص بك',
    'addAccount.connectionMethod': 'طريقة الاتصال',
    'addAccount.qrCode': 'رمز QR',
    'addAccount.pairingCode': 'رمز الإقران',
    'addAccount.qrCodeHelper': 'امسح رمز QR بكاميرا واتساب',
    'addAccount.pairingCodeHelper': 'أدخل الرمز يدوياً في إعدادات واتساب',
    'addAccount.qrHint': 'امسح رمز QR بكاميرا واتساب',
    'addAccount.pairingHint': 'أدخل الرمز يدوياً في إعدادات واتساب',
    'addAccount.phoneNumber': 'رقم الهاتف',
    'addAccount.phoneNumberPlaceholder': '+972501234567',
    'addAccount.phoneNumberHelper': 'قم بتضمين رمز البلد (مثل +1، +972)',
    'addAccount.phoneHint': 'قم بتضمين رمز البلد (مثل +1، +972)',
    'addAccount.accountName': 'اسم الحساب (اختياري)',
    'addAccount.accountNamePlaceholder': 'حساب عملي',
    'addAccount.proxySettings': 'إعدادات البروكسي (اختياري)',
    'addAccount.httpOnly': 'HTTP/HTTPS فقط',
    'addAccount.proxySupported': '✅ مدعوم: بروكسي HTTP/HTTPS مع مصادقة اسم المستخدم وكلمة المرور',
    'addAccount.proxyExample': 'مثال: proxy.example.com:8080 مع اسم مستخدم وكلمة مرور',
    'addAccount.proxyType': 'نوع البروكسي',
    'addAccount.proxyHost': 'عنوان البروكسي',
    'addAccount.proxyHostPlaceholder': 'proxy.example.com',
    'addAccount.proxyPort': 'المنفذ',
    'addAccount.proxyPortPlaceholder': '8080',
    'addAccount.proxyUsername': 'اسم مستخدم البروكسي',
    'addAccount.proxyUsernamePlaceholder': 'اسم مستخدم البروكسي',
    'addAccount.proxyPassword': 'كلمة مرور البروكسي',
    'addAccount.proxyPasswordPlaceholder': 'كلمة مرور البروكسي',
    'addAccount.proxyAuthHelper': 'اترك فارغاً إذا لم تكن هناك مصادقة',
    'addAccount.proxyNote': 'يتم دعم بروكسي HTTP/HTTPS فقط. المصادقة بكلمة المرور مدعومة بالكامل.',
    'addAccount.connecting': 'جارٍ الاتصال...',
    'addAccount.connectButton': 'ربط الحساب',
    'addAccount.submit': 'ربط الحساب',
    'addAccount.scanQR': 'امسح رمز QR',
    'addAccount.enterPairing': 'أدخل هذا الرمز في واتساب',
    'addAccount.done': 'تم',
    'addAccount.errorAdd': 'فشل إضافة الحساب',
    'addAccount.connected': 'تم توصيل الحساب بنجاح!',
    'addAccount.closingAutomatically': 'الإغلاق تلقائياً...',
    
    // Campaigns Page
    'campaigns.title': 'الحملات',
    'campaigns.subtitle': 'إنشاء وإدارة حملات واتساب الخاصة بك',
    'campaigns.createCampaign': 'إنشاء حملة',
    'campaigns.noCampaigns': 'لم يتم إنشاء حملات حتى الآن',
    'campaigns.createFirst': 'إنشاء حملتك الأولى',
    'campaigns.start': 'ابدأ',
    'campaigns.continue': 'متابعة',
    'campaigns.pause': 'إيقاف مؤقت',
    'campaigns.stop': 'إيقاف',
    'campaigns.delete': 'حذف',
    'campaigns.deleteConfirm': 'هل أنت متأكد من حذف هذه الحملة؟ لا يمكن التراجع عن هذا الإجراء.',
    'campaigns.downloadReport': 'تحميل تقرير Excel',
    'campaigns.draft': 'مسودة',
    'campaigns.running': 'قيد التشغيل',
    'campaigns.paused': 'متوقف مؤقتاً',
    'campaigns.completed': 'مكتمل',
    'campaigns.stopped': 'متوقف',
    
    // Create Campaign Page
    'createCampaign.title': 'إنشاء حملة',
    'createCampaign.subtitle': 'إعداد حملتك التسويقية على واتساب',
    'createCampaign.accountsAvailable': '{count} حساب متاح',
    'createCampaign.buttons.discard': 'تجاهل',
    'createCampaign.buttons.launch': 'إطلاق الحملة',
    'createCampaign.buttons.launching': 'جارٍ الإطلاق...',
    'createCampaign.step1.title': 'ماذا سترسل؟',
    'createCampaign.step1.description': 'تكوين هوية الحملة ومحتوى الرسالة',
    'createCampaign.step1.campaignName': 'اسم الحملة',
    'createCampaign.step1.campaignNamePlaceholder': 'مثال: تخفيضات الصيف - عملاء VIP',
    'createCampaign.step1.messageContent': 'محتوى الرسالة',
    'createCampaign.step1.messagePlaceholder': 'مرحباً {{name}}، أردت التواصل بخصوص...',
    'createCampaign.step1.personalizeHint': 'استخدم {{name}} للتخصيص',
    'createCampaign.step1.messageVariantsTitle': 'نسخ الرسالة',
    'createCampaign.step1.addMessageVariant': '+ إضافة نسخة',
    'createCampaign.step1.messageVariantsHint': 'يتم اختيار نسخة واحدة عشوائياً عند كل إرسال',
    'createCampaign.step1.messageVariantLabel': 'نسخة',
    'createCampaign.formatting.bold': 'عريض',
    'createCampaign.formatting.italic': 'مائل',
    'createCampaign.formatting.strikethrough': 'يتوسطه خط',
    'createCampaign.formatting.monospace': 'أحادي المسافة',
    'createCampaign.step2.title': 'لمن سترسل؟',
    'createCampaign.step2.description': 'اختر حسابات الإرسال وعلامات الجمهور المستهدف',
    'createCampaign.step2.sendFromAccounts': 'إرسال من الحسابات',
    'createCampaign.step2.selectAll': 'تحديد الكل',
    'createCampaign.step2.deselectAll': 'إلغاء تحديد الكل',
    'createCampaign.step2.unnamed': 'بدون اسم',
    'createCampaign.step2.targetAudience': 'الجمهور المستهدف (العلامات)',
    'createCampaign.step2.noTags': 'لم يتم العثور على علامات. انتقل إلى جهات الاتصال لإنشاء علامات.',
    'createCampaign.step3.title': 'متى سترسل؟',
    'createCampaign.step3.description': 'تكوين التأخير بين الرسائل والحدود اليومية',
    'createCampaign.step3.delayBetweenMessages': 'التأخير بين الرسائل',
    'createCampaign.step3.minDelay': 'الحد الأدنى للتأخير',
    'createCampaign.step3.maxDelay': 'الحد الأقصى للتأخير',
    'createCampaign.step3.dailyLimit': 'الحد اليومي',
    'createCampaign.step3.msgsPerAccount': 'رسائل / حساب',
    'createCampaign.step3.workingHours': 'ساعات العمل',
    'createCampaign.step3.startTime': 'وقت البدء',
    'createCampaign.step3.endTime': 'وقت النهاية',
    'createCampaign.step3.alwaysOn': 'نشط دائماً (24/7)',
    'createCampaign.step3.set24_7': 'تعيين 24/7',
    'createCampaign.preview.title': 'معاينة مباشرة',
    'createCampaign.preview.whatsappWeb': 'واتساب ويب',
    'createCampaign.summary.title': 'ملخص الحملة',
    'createCampaign.summary.selectedAccounts': 'الحسابات المحددة',
    'createCampaign.summary.targetTags': 'علامات الهدف',
    'createCampaign.summary.estDailyVolume': 'الحجم اليومي المقدر',
    'createCampaign.summary.msgsCount': '~{count} رسالة',
    'createCampaign.validation.campaignNameRequired': 'يرجى إدخال اسم الحملة',
    'createCampaign.validation.messageRequired': 'يرجى إدخال رسالة',
    'createCampaign.validation.accountRequired': 'يرجى تحديد حساب واحد على الأقل',
    'createCampaign.validation.tagRequired': 'يرجى تحديد علامة واحدة على الأقل',
    'createCampaign.toast.success': 'تم إنشاء الحملة بنجاح!',
    'createCampaign.toast.error': 'فشل إنشاء الحملة',
    'createCampaign.whatsappPreview.contactName': 'أحمد محمد',
    'createCampaign.whatsappPreview.online': 'متصل',
    'createCampaign.whatsappPreview.today': 'اليوم',
    'createCampaign.whatsappPreview.defaultMessage': 'مرحباً! تحقق من عروضنا الجديدة.',
    'createCampaign.whatsappPreview.inputPlaceholder': 'رسالة',
    'createCampaign.scheduling.enableScheduling': 'جدولة الحملة لوقت لاحق',
    'createCampaign.scheduling.startDateTime': 'تاريخ ووقت البدء',
    'createCampaign.scheduling.scheduledFor': 'مجدولة لـ {datetime}',
    
    // Inbox Page
    'inbox.title': 'صندوق الوارد',
    'inbox.searchChats': 'البحث في المحادثات...',
    'inbox.allStatus': 'جميع الحالات',
    'inbox.unhandled': 'غير معالج',
    'inbox.handled': 'معالج',
    'inbox.allAccounts': 'جميع الحسابات',
    'inbox.chats': 'محادثات',
    'inbox.selectChat': 'حدد محادثة لبدء المراسلة',
    'inbox.manageConversations': 'إدارة جميع محادثات واتساب الخاصة بك في مكان واحد',
    'inbox.markHandled': 'وضع علامة معالج',
    'inbox.typeMessage': 'اكتب رسالة...',
    'inbox.sendMessage': 'إرسال رسالة',
    'inbox.attachFile': 'إرفاق ملف',
    'inbox.noChats': 'لم يتم العثور على محادثات',
    
    // Media types for inbox preview
    'inbox.media.image': 'صورة',
    'inbox.media.video': 'فيديو',
    'inbox.media.audio': 'تسجيل صوتي',
    'inbox.media.document': 'ملف',
    
    // Contacts Page
    'contacts.title': 'جهات الاتصال',
    'contacts.subtitle': 'إدارة قائمة جهات الاتصال والعلامات الخاصة بك',
    'contacts.importContacts': 'استيراد جهات الاتصال',
    'contacts.exportContacts': 'تصدير جهات الاتصال',
    'contacts.downloadSample': 'تحميل نموذج',
    'contacts.noContacts': 'لم يتم العثور على جهات اتصال',
    'contacts.deleteContact': 'حذف جهة الاتصال؟',
    'contacts.deleteConfirm': 'هل أنت متأكد من حذف جهة الاتصال هذه؟ لا يمكن التراجع عن هذا الإجراء.',
    'contacts.manageTags': 'إدارة العلامات',
    'contacts.phoneNumber': 'رقم الهاتف',
    'contacts.tags': 'العلامات',
    'contacts.createdAt': 'تم الإنشاء في',
    'contacts.importTitle': 'استيراد جهات الاتصال',
    'contacts.importDesc': 'تحميل ملف CSV أو XLSX بأعمدة: phone_number، name (اختياري)، tags (اختياري - مفصولة بفواصل)',
    'contacts.selectFile': 'اختر ملف',
    'contacts.selected': 'محدد',
    'contacts.importing': 'جارٍ الاستيراد...',
    'contacts.manageTagsFor': 'إدارة العلامات لـ {name}',
    'contacts.availableTags': 'العلامات المتاحة',
    'contacts.newTag': 'علامة جديدة',
    'contacts.tagName': 'اسم العلامة',
    'contacts.createTag': 'إنشاء',
    'contacts.noTags': 'لا توجد علامات متاحة',
    'contacts.deleteTag': 'حذف العلامة؟',
    'contacts.deleteTagConfirm': 'هل أنت متأكد من حذف هذه العلامة؟ سيتم إزالتها من جميع جهات الاتصال.',
    'contacts.done': 'تم',
    'contacts.unknownContact': 'جهة اتصال غير معروفة',
    'contacts.added': 'تم الإضافة في',
    'contacts.noTagsForContact': 'لا توجد علامات',
    'contacts.manageTagsTooltip': 'إدارة العلامات',
    'contacts.deleteContactTooltip': 'حذف جهة الاتصال',
    'contacts.importSuccess': 'تم استيراد {count} جهة اتصال بنجاح',
    'contacts.blacklistInfo': 'جهات الاتصال ذات علامة BlackList لن تتلقى رسائل من الحملات. استخدم هذا لمنع الإرسال إلى جهات اتصال معينة.',
    'contacts.systemTag': 'نظام',
    'contacts.cannotDeleteSystem': 'لا يمكن حذف علامة النظام',
    'contacts.addManually': 'إضافة جهة اتصال',
    'contacts.addContact': 'إضافة جهة اتصال جديدة',
    'contacts.contactName': 'اسم جهة الاتصال',
    'contacts.selectTag': 'اختر علامة (اختياري)',
    'contacts.addSuccess': 'تمت إضافة جهة الاتصال بنجاح',
    'contacts.phoneRequired': 'رقم الهاتف مطلوب',
    'contacts.phoneInvalid': 'الرجاء إدخال رقم هاتف صالح',
    'contacts.pasteNumbers': 'لصق الأرقام',
    'contacts.pasteNumbersTitle': 'لصق أرقام الهاتف',
    'contacts.pasteNumbersDesc': 'الصق قائمة بأرقام الهاتف (واحد في كل سطر أو مفصولة بفواصل)',
    'contacts.pasteHere': 'الصق أرقام الهاتف هنا...',
    'contacts.fromFile': 'من ملف',
    'contacts.fromPaste': 'لصق القائمة',
    'contacts.numbersFound': 'تم العثور على {count} رقم',
    
    // Warm-up Page
    'warmup.title': 'إحماء الحسابات',
    'warmup.subtitle': 'تسخين حساباتك تدريجياً لتجنب الحظر',
    'warmup.configure': 'تكوين جلسة الإحماء',
    'warmup.selectAccounts': 'اختر الحسابات (الحد الأدنى 2)',
    'warmup.selected': 'محدد',
    'warmup.minDelay': 'الحد الأدنى للتأخير (ثواني)',
    'warmup.maxDelay': 'الحد الأقصى للتأخير (ثواني)',
    'warmup.minutes': 'دقائق',
    'warmup.smartLimits': 'تطبيق الحدود الذكية:',
    'warmup.maxMessages': 'بحد أقصى 40 رسالة لكل حساب في اليوم',
    'warmup.activeHours': 'ساعات النشاط: 8:00 صباحاً - 10:00 مساءً',
    'warmup.parallelWork': 'جميع الحسابات تعمل بالتوازي',
    'warmup.autoReset': 'إعادة تعيين تلقائية في منتصف الليل',
    'warmup.startSession': 'بدء جلسة الإحماء',
    'warmup.stopSession': 'إيقاف الجلسة',
    'warmup.sessionActive': 'جلسة الإحماء نشطة',
    'warmup.messagesSent': 'الرسائل المرسلة اليوم',
    'warmup.nextMessage': 'الرسالة التالية بعد',
    'warmup.noActiveSession': 'لا توجد جلسة إحماء نشطة',
    'warmup.statistics': 'إحصائيات الإحماء',
    'warmup.totalSent': 'المجموع المرسل',
    'warmup.lastMessage': 'آخر رسالة',
    'warmup.recentActivity': 'النشاط الأخير',
    'warmup.sentFrom': 'أرسلت من',
    'warmup.sentTo': 'إلى',
    'warmup.noActivity': 'لا يوجد نشاط إحماء حتى الآن',
    'warmup.sessionHistory': 'سجل الجلسات',
    'warmup.viewDetails': 'عرض التفاصيل',
    'warmup.messagesInSession': 'رسائل',
    'warmup.accountsParticipated': 'حسابات',
    'warmup.sessionDetails': 'تفاصيل الجلسة',
    'warmup.accountBreakdown': 'التفصيل حسب الحساب',
    
    // Message Templates
    templates: 'قوالب الرسائل',
    'templates.title': 'قوالب الرسائل',
    'templates.subtitle': 'إنشاء وإدارة قوالب الرسائل القابلة لإعادة الاستخدام',
    'templates.createNew': 'إنشاء قالب',
    'templates.noTemplates': 'لا توجد قوالب حتى الآن. قم بإنشاء قالب رسالتك الأول!',
    'templates.templateName': 'اسم القالب',
    'templates.messageContent': 'محتوى الرسالة',
    'templates.editTemplate': 'تحرير القالب',
    'templates.deleteTemplate': 'حذف القالب',
    'templates.deleteConfirm': 'هل أنت متأكد من حذف هذا القالب؟',
    'templates.useTemplate': 'استخدام القالب',
    'templates.loadTemplate': 'تحميل القالب',
    'templates.selectTemplate': 'اختر قالب',
    
    // Automation Flows
    flows: 'تدفقات الأتمتة',
    'flows.title': 'تدفقات الأتمتة',
    'flows.subtitle': 'إنشاء روبوتات تلقائية للرد على الرسائل الواردة',
    'flows.createNew': 'إنشاء تدفق جديد',
    'flows.editFlow': 'تحرير التدفق',
    'flows.flowName': 'اسم التدفق',
    'flows.flowDescription': 'الوصف',
    'flows.selectAccounts': 'اختر الحسابات',
    'flows.activeFlow': 'نشط',
    'flows.inactiveFlow': 'غير نشط',
    'flows.deleteFlow': 'حذف التدفق',
    'flows.deleteConfirm': 'هل أنت متأكد من حذف هذا التدفق؟',
    'flows.noFlows': 'لا توجد تدفقات حتى الآن. قم بإنشاء تدفق تلقائي أول!',
    'flows.saveFlow': 'حفظ التدفق',
    'flows.nodeTypes': 'أنواع العقد',
    'flows.conditions': 'الشروط',
    'flows.actions': 'الإجراءات',
    'flows.ifContains': 'إذا يحتوي',
    'flows.ifEquals': 'إذا يساوي',
    'flows.ifLastMessageOlderThan': 'إذا كانت آخر رسالة أقدم من',
    'flows.hours': 'ساعات',
    'flows.minutes': 'دقائق',
    'flows.sendMessage': 'إرسال رسالة',
    'flows.autoReply': 'رد تلقائي',
    'flows.forwardMessage': 'إرسال إلى رقم آخر',
    'flows.delay': 'تأخير',
    'flows.randomDelay': 'تأخير عشوائي',
    'flows.typing': 'الكتابة',
    'flows.blacklist': 'إضافة إلى القائمة السوداء',
    'flows.blacklistDescription': 'إضافة جهة الاتصال هذه إلى القائمة السوداء',
    'flows.enterText': 'أدخل النص للمطابقة',
    'flows.enterMessage': 'أدخل الرسالة للإرسال',
    'flows.destinationNumber': 'رقم الوجهة',
    'flows.enterDestinationNumber': 'أدخل رقم الهاتف',
    'flows.messageVariables': 'متغيرات الرسالة',
    'flows.insertIncomingMessage': 'إدراج الرسالة الواردة',
    'flows.insertSenderPhone': 'إدراج رقم المرسل',
    'flows.seconds': 'ثواني',
    'flows.minSeconds': 'الحد الأدنى (ثواني)',
    'flows.maxSeconds': 'الحد الأقصى (ثواني)',
    'flows.selectMedia': 'اختر الوسائط (اختياري)',
    'flows.caption': 'التعليق',
    'flows.dragNodes': 'اسحب العقد هنا لبناء التدفق',
    'flows.connectNodes': 'ربط العقد لإنشاء منطق التشغيل الآلي',
    'flows.yes': 'نعم',
    'flows.no': 'لا',
    'flows.next': 'التالي',
    'flows.duplicate': 'تكرار',
    'flows.remove': 'إزالة',
    'flows.selectAll': 'اختر الكل',
    'flows.clearAll': 'مسح الكل',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLang = localStorage.getItem('app-language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'he')) {
      setLanguageState(savedLang);
      applyLanguage(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    applyLanguage(lang);
  };

  const applyLanguage = (lang: Language) => {
    const dir = (lang === 'he' || lang === 'ar') ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
    
    // Add RTL class for styling
    if (lang === 'he' || lang === 'ar') {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
  };

  const t = (key: string): string => {
    const translation = (translations[language] as any)[key];
    return translation !== undefined ? translation : key;
  };

  const dir = (language === 'he' || language === 'ar') ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
